/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasNewIndexRouteImport } from './routes/ideas/new/index'
import { Route as IdeasIdeaidIndexRouteImport } from './routes/ideas/$ideaid/index'
import { Route as IdeasIdeaidEditRouteImport } from './routes/ideas/$ideaid/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewIndexRoute = IdeasNewIndexRouteImport.update({
  id: '/ideas/new/',
  path: '/ideas/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaidIndexRoute = IdeasIdeaidIndexRouteImport.update({
  id: '/ideas/$ideaid/',
  path: '/ideas/$ideaid/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaidEditRoute = IdeasIdeaidEditRouteImport.update({
  id: '/ideas/$ideaid/edit',
  path: '/ideas/$ideaid/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$ideaid/edit': typeof IdeasIdeaidEditRoute
  '/ideas/$ideaid/': typeof IdeasIdeaidIndexRoute
  '/ideas/new/': typeof IdeasNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/ideas/$ideaid/edit': typeof IdeasIdeaidEditRoute
  '/ideas/$ideaid': typeof IdeasIdeaidIndexRoute
  '/ideas/new': typeof IdeasNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$ideaid/edit': typeof IdeasIdeaidEditRoute
  '/ideas/$ideaid/': typeof IdeasIdeaidIndexRoute
  '/ideas/new/': typeof IdeasNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas/'
    | '/ideas/$ideaid/edit'
    | '/ideas/$ideaid/'
    | '/ideas/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ideas' | '/ideas/$ideaid/edit' | '/ideas/$ideaid' | '/ideas/new'
  id:
    | '__root__'
    | '/'
    | '/ideas/'
    | '/ideas/$ideaid/edit'
    | '/ideas/$ideaid/'
    | '/ideas/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  IdeasIdeaidEditRoute: typeof IdeasIdeaidEditRoute
  IdeasIdeaidIndexRoute: typeof IdeasIdeaidIndexRoute
  IdeasNewIndexRoute: typeof IdeasNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/new/': {
      id: '/ideas/new/'
      path: '/ideas/new'
      fullPath: '/ideas/new/'
      preLoaderRoute: typeof IdeasNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaid/': {
      id: '/ideas/$ideaid/'
      path: '/ideas/$ideaid'
      fullPath: '/ideas/$ideaid/'
      preLoaderRoute: typeof IdeasIdeaidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaid/edit': {
      id: '/ideas/$ideaid/edit'
      path: '/ideas/$ideaid/edit'
      fullPath: '/ideas/$ideaid/edit'
      preLoaderRoute: typeof IdeasIdeaidEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  IdeasIdeaidEditRoute: IdeasIdeaidEditRoute,
  IdeasIdeaidIndexRoute: IdeasIdeaidIndexRoute,
  IdeasNewIndexRoute: IdeasNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
